# Generated by Django 4.2.3 on 2023-07-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerequest',
            name='file',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
